#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 30000" \
        s6-setuidgid abc minetestserver --port 30000 \
        --config /config/.minetest/main-config/minetest.conf ${CLI_ARGS}
