#!/usr/bin/with-contenv bash

# predefine some variables
WORLD_PART="--worldname "
GAMEID_PART="--gameid "

# shellcheck disable=SC2154
WORLD_SET=$WORLD
GAMEID_SET=$GAMEID

# set WORLD_STRING variable to use user-defined world or default world.
if [ -z "$WORLD" ]; then
WORLD_STRING=" "
else
WORLD_STRING=$wWORLD_PART$WORLD_SET
fi

# set GAMEID_STRING variable to use user-defined Gameid.
if [ -z "$GAMEID" ]; then
GAMEID_STRING=" "
else
GAMEID_STRING=$GAMEID_PART$GAMEID_SET
fi

# shellcheck disable=SC2086
exec \
	s6-setuidgid abc minetestserver $WORLD_STRING $GAMEID_STRING \
	--config /config/.minetest/main-config/minetest.conf --port 30000
