#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
    /config/.minetest/games \
    /config/.minetest/mods \
    /config/.minetest/main-config

if [[ ! -f "/config/.minetest/main-config/minetest.conf" ]]; then
    cp /defaults/minetest.conf /config/.minetest/main-config/minetest.conf
fi

if [[ ! -d "/config/.minetest/games/minimal" ]]; then
    cp -pr /defaults/games/* /config/.minetest/games/
fi

# permissions
lsiown -R abc:abc \
    /config
